### ISSUE TITLE
Add the Tetris rate somewhere in the overlayed stats.

### ISSUE THREAD

**Issue by r002** [timotheeg/tetris_ctm_summary#1]
From yobi9's Discord comment on 3/10/21:

> Add the Tetris rate somewhere in the overlayed stats. I understand the pace metrics supersedes the TRT in a way, but I think folks do like the TRT (**_I_** Like the TRT!). The method to get the TRT label is already there in the `Player` class (comes from the [tetris_rate_adder repo](https://github.com/timotheeg/tetris_rate_adder)), and I thought maybe there could be an option to add it somewhere in the overlayed stats too.

**Comment by timotheeg** [comment]
Fixed by https://github.com/timotheeg/tetris_ctm_summary/pull/7
