### ISSUE TITLE
License

### ISSUE THREAD

**Issue by micwoj92** [timotheeg/tetris_ctm_summary#15]
Hello, I am coming from  aGameScout's video. In the video he said that you release that as as open source project, however this is false because this software has no license. choosealicense.com, a page made by GitHub says following about software with no license "that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose."

Could you please add a license to this code? I don't want for people to break any laws. Thanks.

**Comment by timotheeg** [comment]
Done
https://github.com/timotheeg/tetris_ctm_summary/commit/b3270015f7639d8a765aa1bc51f8ad7ec22114b9
